### ISSUE TITLE
Errata Page References wrong...

### ISSUE THREAD

**Issue by ArmandoMobileVoid** [PacktPublishing/Mastering-Quantum-Computing-with-IBM-QX#1]
Hello,

All the Page references in the Errata that start after page 220 are off by 7 pages, for example the errata for page 220 is actually on page 227. When compared to the paperback version of the book.

**Comment by ManikandanKurup-Packt** [comment]
Thank you for pointing it out! @ArmandoMobileVoid 
I have made the changes to the README. Cheers!
