### ISSUE TITLE
chapter01

### ISSUE THREAD

**Issue by 3625365git-tx** [PacktPublishing/Mastering-Quantum-Computing-with-IBM-QX#5]
This error occurred after running the code. Is this  url link valid?
"HTTPError: 404 Client Error: Not Found for url: https://quantumexperience.ng.bluemix.net/api/users/loginWithToken"

**Comment by sarvesh-packt** [comment]
Hi @3625365git-tx,

I did not find the link which you mentioned in your issue but found this link https://quantumexperience.ng.bluemix.net/qx/signup in the first chapter. Kindly refer this link and also check **API key** section from chapter one which might be helpful for you to generate the API token.

Regards,
